- name: install the mariadb server and mysql-python
  yum: name={{ item }} state=installed
  with_items:
  - MySQL-python
  - mariadb
  - mariadb-server
  tags: mariadb

- name: mariadb service state
  service: name=mariadb state=started enabled=yes
  tags: mariadb

# note: 'localhost' needs to be the last item for idempotency
- name: update mariadb root password for all root accounts
  mysql_user: name=root host={{ item }} password={{ mysql_root_password }} priv=*.*:ALL,GRANT
  with_items:
    - "%"
    - "127.0.0.1"
    - "::1"
    - "localhost"
  tags: mariadb

- name: setup .my.cnf file with root password credentials
  template: src=root-my-cnf.j2 dest=/root/.my.cnf owner=root mode=0600
  tags: mariadb

- name: delete anonymous user for localhost
  action: mysql_user user="" state="absent"
  tags: mariadb

- name: remove the mariadb test database
  action: mysql_db db=test state=absent
  tags: mariadb
